export const ACCOUNTS = {
  summary: {
    total: 8,
    active: 5,
    atRisk: 3,
    renewalsThisQuarter: 3,
  },
  list: [
    {
      id: "northloop-metals",
      name: "Northloop Metals",
      owner: "Jamie Fox",
      segment: "Strategic",
      status: "Active",
      health: "Healthy",
      arr: 210000,
      renewalDate: "2025-09-12",
      primaryPlant: "Gary, IN",
      productFocus: "Recycled aluminum billet & extrusion",
      certifications: "ASI, ISO 14001, ISO 9001",
      leadTime: "6-8 weeks",
      incoterms: "FOB Chicago",
      shippingMode: "Rail + Truckload",
      preferredCarrier: "BNSF Logistics",
      warehouseRegion: "Great Lakes",
      paymentTerms: "Net 45",
      minOrderValue: 80000,
      contractTerm: "36 months",
      forecastCadence: "Monthly",
      primaryFacilityId: "FAC-CHI-01",
      circularityProgram: "Closed-loop aluminum buyback",
      takebackRate: "72%",
      recycledContentTarget: "65% by 2026",
      epcisMaturity: "EPCIS 2.0 live",
      activeShipmentIds: ["SHIP-1007"],
      materialStreamIds: ["MAT-AL-5083", "MAT-STEEL-CR"],
      keyAssetIds: ["RTI-0007"],
      openTaskIds: ["TASK-2301", "TASK-2462"],
    },
    {
      id: "blueriver-plastics",
      name: "BlueRiver Plastics",
      owner: "Priya Shah",
      segment: "Enterprise",
      status: "At Risk",
      health: "Watch",
      arr: 98000,
      renewalDate: "2025-05-02",
      primaryPlant: "Portland, OR",
      productFocus: "Food-grade rPET and rHDPE compounds",
      certifications: "ISCC+, ISO 14001, UL 2809",
      leadTime: "7-9 weeks",
      incoterms: "DAP Seattle",
      shippingMode: "Truckload",
      preferredCarrier: "XPO Logistics",
      warehouseRegion: "Pacific Northwest",
      paymentTerms: "Net 60",
      minOrderValue: 45000,
      contractTerm: "24 months",
      forecastCadence: "Monthly",
      primaryFacilityId: "FAC-PDX-04",
      circularityProgram: "Food-grade PET loop",
      takebackRate: "48%",
      recycledContentTarget: "50% by 2025",
      epcisMaturity: "Pilot (ObjectEvent only)",
      activeShipmentIds: ["SHIP-1011"],
      materialStreamIds: ["MAT-PET-R30", "MAT-PP-REGRIND"],
      keyAssetIds: ["RTI-0108"],
      openTaskIds: ["TASK-2312", "TASK-2470"],
    },
    {
      id: "greenpulse-batteries",
      name: "GreenPulse Batteries",
      owner: "Nina Patel",
      segment: "Strategic",
      status: "At Risk",
      health: "Watch",
      arr: 189000,
      renewalDate: "2025-07-03",
      primaryPlant: "Detroit, MI",
      productFocus: "EV battery pack refurbishment",
      certifications: "R2v3, ISO 9001",
      leadTime: "10-12 weeks",
      incoterms: "DAP Detroit",
      shippingMode: "Hazmat LTL",
      preferredCarrier: "FedEx Freight",
      warehouseRegion: "Great Lakes",
      paymentTerms: "Net 45",
      minOrderValue: 60000,
      contractTerm: "36 months",
      forecastCadence: "Monthly",
      primaryFacilityId: "FAC-DET-03",
      circularityProgram: "Battery second-life grading",
      takebackRate: "61%",
      recycledContentTarget: "30% by 2027",
      epcisMaturity: "EPCIS 2.0 + sensor data",
      activeShipmentIds: ["SHIP-1014"],
      materialStreamIds: ["MAT-NMC-R"],
      keyAssetIds: ["BAT-1001"],
      openTaskIds: ["TASK-2352", "TASK-2392"],
    },
    {
      id: "atlas-remanufacturing",
      name: "Atlas Remanufacturing",
      owner: "Evan Reed",
      segment: "Strategic",
      status: "Active",
      health: "Healthy",
      arr: 156000,
      renewalDate: "2025-11-30",
      primaryPlant: "Tucson, AZ",
      productFocus: "Remanufactured industrial gearboxes",
      certifications: "ISO 9001, ISO 14001",
      leadTime: "8-10 weeks",
      incoterms: "FOB Phoenix",
      shippingMode: "LTL",
      preferredCarrier: "Old Dominion",
      warehouseRegion: "Southwest",
      paymentTerms: "Net 60",
      minOrderValue: 50000,
      contractTerm: "24 months",
      forecastCadence: "Quarterly",
      primaryFacilityId: "FAC-TUS-06",
      circularityProgram: "Core return & rebuild",
      takebackRate: "83%",
      recycledContentTarget: "40% by 2026",
      epcisMaturity: "Transactional events only",
      activeShipmentIds: ["SHIP-1022"],
      materialStreamIds: ["MAT-STEEL-CR"],
      keyAssetIds: ["RTI-0214"],
      openTaskIds: ["TASK-2381", "TASK-2420"],
    },
    {
      id: "reclaim-robotics",
      name: "Reclaim Robotics",
      owner: "Sofia Ramirez",
      segment: "Mid-Market",
      status: "Active",
      health: "Healthy",
      arr: 54000,
      renewalDate: "2025-10-21",
      primaryPlant: "Austin, TX",
      productFocus: "Remanufactured automation cells",
      certifications: "ISO 9001, UL 508A",
      leadTime: "9-11 weeks",
      incoterms: "FOB Dallas",
      shippingMode: "Truckload",
      preferredCarrier: "Schneider",
      warehouseRegion: "South Central",
      paymentTerms: "Net 30",
      minOrderValue: 30000,
      contractTerm: "18 months",
      forecastCadence: "Quarterly",
      primaryFacilityId: "FAC-AUS-05",
      circularityProgram: "Robot cell refurbishment",
      takebackRate: "54%",
      recycledContentTarget: "25% by 2026",
      epcisMaturity: "EPCIS 2.0 roadmap",
      activeShipmentIds: null,
      materialStreamIds: ["MAT-STEEL-CR"],
      keyAssetIds: ["EQ-3305"],
      openTaskIds: ["TASK-2370"],
    },
    {
      id: "circular-dynamics",
      name: "Circular Dynamics",
      owner: "Marcus Lee",
      segment: "Mid-Market",
      status: "Churn Risk",
      health: "Critical",
      arr: 32000,
      renewalDate: "2025-04-05",
      primaryPlant: "Rotterdam, NL",
      productFocus: "Reclaimed carbon fiber prepregs",
      certifications: "ISO 14001",
      leadTime: "10-12 weeks",
      incoterms: "DAP Rotterdam",
      shippingMode: "Ocean + Truck",
      preferredCarrier: "Maersk",
      warehouseRegion: "EU Hub",
      paymentTerms: "Net 60",
      minOrderValue: 25000,
      contractTerm: "12 months",
      forecastCadence: "Monthly",
      primaryFacilityId: "FAC-RTM-02",
      circularityProgram: "Composite recovery & resale",
      takebackRate: "37%",
      recycledContentTarget: "70% by 2027",
      epcisMaturity: "Not started",
      activeShipmentIds: ["SHIP-1030"],
      materialStreamIds: ["MAT-CF-RECL"],
      keyAssetIds: null,
      openTaskIds: ["TASK-2515"],
    },
    {
      id: "ecovia-logistics",
      name: "EcoVia Logistics",
      owner: "Sara Bennett",
      segment: "Enterprise",
      status: "Active",
      health: "Healthy",
      arr: 47000,
      renewalDate: "2025-08-19",
      primaryPlant: "Rotterdam, NL",
      productFocus: "Circular 3PL & reverse logistics",
      certifications: "ISO 14001, ISO 9001",
      leadTime: "48-72 hours",
      incoterms: "DAP Rotterdam",
      shippingMode: "Multimodal",
      preferredCarrier: "DHL Supply Chain",
      warehouseRegion: "EMEA",
      paymentTerms: "Net 30",
      minOrderValue: 15000,
      contractTerm: "18 months",
      forecastCadence: "Monthly",
      primaryFacilityId: "FAC-RTM-02",
      circularityProgram: "Reusable packaging pool",
      takebackRate: "92%",
      recycledContentTarget: "Reusable fleet 92% return rate",
      epcisMaturity: "EPCIS 2.0 live",
      activeShipmentIds: ["SHIP-1007", "SHIP-1011", "SHIP-1030"],
      materialStreamIds: ["MAT-PP-REGRIND"],
      keyAssetIds: ["RTI-0007", "RTI-0108"],
      openTaskIds: ["TASK-2493"],
    },
    {
      id: "aurora-composites",
      name: "Aurora Composites",
      owner: "Zoe Martinez",
      segment: "Mid-Market",
      status: "Active",
      health: "Healthy",
      arr: 62000,
      renewalDate: "2025-12-02",
      primaryPlant: "Monterrey, MX",
      productFocus: "Lightweight structural composites",
      certifications: "ISO 9001, IATF 16949",
      leadTime: "8-10 weeks",
      incoterms: "FOB Houston",
      shippingMode: "Truckload",
      preferredCarrier: "Schneider",
      warehouseRegion: "Gulf Coast",
      paymentTerms: "Net 45",
      minOrderValue: 35000,
      contractTerm: "24 months",
      forecastCadence: "Quarterly",
      primaryFacilityId: "FAC-MTY-07",
      circularityProgram: "Trim scrap recovery",
      takebackRate: "44%",
      recycledContentTarget: "20% by 2026",
      epcisMaturity: "EPCIS 1.2 legacy",
      activeShipmentIds: ["SHIP-1014"],
      materialStreamIds: ["MAT-STEEL-CR", "MAT-CF-RECL"],
      keyAssetIds: null,
      openTaskIds: ["TASK-2411"],
    },
  ],
};
