export const BATCHES = {
  list: [
    {
      id: "LOT-AL-25-040",
      materialId: "MAT-AL-5083",
      quantity: "21,500 kg",
      disposition: "available",
      bizStep: "commissioning",
      productionDate: "2025-02-26",
      facilityId: "FAC-CHI-01",
      ownerAccountId: "northloop-metals",
      shipmentIds: null,
      transformationId: "TR-AL-2025-040",
      inputBatchIds: null,
      outputBatchIds: ["LOT-AL-25-041"],
      eventIds: null,
      storageLocation: "Yard A / Bay 11",
    },
    {
      id: "LOT-AL-25-039",
      materialId: "MAT-AL-5083",
      quantity: "19,200 kg",
      disposition: "in_progress",
      bizStep: "transforming",
      productionDate: "2025-02-22",
      facilityId: "FAC-CHI-01",
      ownerAccountId: "northloop-metals",
      shipmentIds: null,
      transformationId: "TR-AL-2025-039",
      inputBatchIds: null,
      outputBatchIds: ["LOT-AL-25-042"],
      eventIds: null,
      storageLocation: "Smelter line 1",
    },
    {
      id: "LOT-AL-25-041",
      materialId: "MAT-AL-5083",
      quantity: "24,000 kg",
      disposition: "available",
      bizStep: "commissioning",
      productionDate: "2025-03-01",
      facilityId: "FAC-CHI-01",
      ownerAccountId: "northloop-metals",
      shipmentIds: ["SHIP-1007"],
      transformationId: "TR-AL-2025-041",
      inputBatchIds: ["LOT-AL-25-040"],
      outputBatchIds: null,
      eventIds: ["EVT-2025-0001", "EVT-2025-0002"],
      storageLocation: "Yard A / Bay 12",
    },
    {
      id: "LOT-AL-25-042",
      materialId: "MAT-AL-5083",
      quantity: "18,500 kg",
      disposition: "in_progress",
      bizStep: "transforming",
      productionDate: "2025-03-04",
      facilityId: "FAC-CHI-01",
      ownerAccountId: "northloop-metals",
      shipmentIds: null,
      transformationId: "TR-AL-2025-042",
      inputBatchIds: ["LOT-AL-25-039"],
      outputBatchIds: null,
      eventIds: null,
      storageLocation: "Smelter line 2",
    },
    {
      id: "LOT-PET-25-010",
      materialId: "MAT-PET-R30",
      quantity: "12,000 kg",
      disposition: "non_conformant",
      bizStep: "inspecting",
      productionDate: "2025-03-07",
      facilityId: "FAC-PDX-04",
      ownerAccountId: "blueriver-plastics",
      shipmentIds: ["SHIP-1011"],
      transformationId: null,
      inputBatchIds: null,
      outputBatchIds: null,
      eventIds: null,
      storageLocation: "Quarantine cage Q3",
    },
    {
      id: "LOT-NMC-25-002",
      materialId: "MAT-NMC-R",
      quantity: "4,800 kg",
      disposition: "in_progress",
      bizStep: "transforming",
      productionDate: "2025-03-10",
      facilityId: "FAC-DET-03",
      ownerAccountId: "greenpulse-batteries",
      shipmentIds: ["SHIP-1014"],
      transformationId: "TR-NMC-2025-002",
      inputBatchIds: null,
      outputBatchIds: null,
      eventIds: ["EVT-2025-0006"],
      storageLocation: "Cathode line B",
    },
    {
      id: "LOT-STEEL-25-007",
      materialId: "MAT-STEEL-CR",
      quantity: "32,000 kg",
      disposition: "damaged",
      bizStep: "receiving",
      productionDate: "2025-03-09",
      facilityId: "FAC-MTY-07",
      ownerAccountId: "aurora-composites",
      shipmentIds: ["SHIP-1022"],
      transformationId: null,
      inputBatchIds: null,
      outputBatchIds: null,
      eventIds: null,
      storageLocation: "Dock 4",
    },
    {
      id: "LOT-PP-25-019",
      materialId: "MAT-PP-REGRIND",
      quantity: "9,500 kg",
      disposition: "in_transit",
      bizStep: "shipping",
      productionDate: "2025-03-02",
      facilityId: "FAC-RTM-02",
      ownerAccountId: "ecovia-logistics",
      shipmentIds: ["SHIP-1007"],
      transformationId: null,
      inputBatchIds: null,
      outputBatchIds: null,
      eventIds: ["EVT-2025-0003"],
      storageLocation: "Outbound staging",
    },
    {
      id: "LOT-CF-25-003",
      materialId: "MAT-CF-RECL",
      quantity: "1,250 kg",
      disposition: "available",
      bizStep: "receiving",
      productionDate: "2025-02-26",
      facilityId: "FAC-RTM-02",
      ownerAccountId: "circular-dynamics",
      shipmentIds: ["SHIP-1030"],
      transformationId: null,
      inputBatchIds: null,
      outputBatchIds: null,
      eventIds: null,
      storageLocation: "Composite vault",
    },
  ],
};
