export const DASHBOARD = {
  metrics: {
    totalRevenue: 1250,
    newCustomers: 1234,
    activeAccounts: 45678,
    growthRate: 0.045,
  },
  visitors: [
    { label: "Apr 2", value: 120 },
    { label: "Apr 7", value: 180 },
    { label: "Apr 12", value: 140 },
    { label: "Apr 17", value: 220 },
    { label: "Apr 22", value: 160 },
    { label: "Apr 27", value: 240 },
    { label: "May 2", value: 210 },
    { label: "May 7", value: 260 },
    { label: "May 12", value: 190 },
    { label: "May 17", value: 280 },
    { label: "May 22", value: 230 },
    { label: "May 27", value: 300 },
  ],
  sections: [
    {
      title: "Cover page",
      type: "Cover page",
      status: "In Progress",
      target: 18,
      limit: 5,
      reviewer: "Eddie Lake",
    },
    {
      title: "Table of contents",
      type: "Table of contents",
      status: "Done",
      target: 29,
      limit: 24,
      reviewer: "Eddie Lake",
    },
    {
      title: "Executive summary",
      type: "Narrative",
      status: "Done",
      target: 10,
      limit: 13,
      reviewer: "Eddie Lake",
    },
    {
      title: "Technical approach",
      type: "Narrative",
      status: "Done",
      target: 27,
      limit: 23,
      reviewer: "Jamik Tashpulatov",
    },
    {
      title: "Design",
      type: "Narrative",
      status: "In Progress",
      target: 2,
      limit: 16,
      reviewer: "Jamik Tashpulatov",
    },
  ],
};
