export const EPCIS = {
  events: [
    {
      id: "EVT-2025-0001",
      eventType: "ObjectEvent",
      bizStep: "commissioning",
      disposition: "available",
      action: "ADD",
      eventTime: "2025-03-01T10:12:00Z",
      readPointId: "FAC-CHI-01",
      bizTransaction: "PO-45219",
      shipmentId: null,
      batchIds: ["LOT-AL-25-041"],
      assetIds: null,
      transformationId: null,
      inputBatchIds: null,
      outputBatchIds: null,
      epcList: ["urn:epc:id:sscc:0614141.1234567890"],
      quantityList: null,
    },
    {
      id: "EVT-2025-0002",
      eventType: "TransformationEvent",
      bizStep: "transforming",
      disposition: "in_progress",
      action: "OBSERVE",
      eventTime: "2025-03-02T14:30:00Z",
      readPointId: "FAC-CHI-01",
      bizTransaction: "WO-8821",
      shipmentId: null,
      batchIds: null,
      assetIds: null,
      transformationId: "TR-AL-2025-041",
      inputBatchIds: ["LOT-AL-25-040"],
      outputBatchIds: ["LOT-AL-25-041"],
      epcList: null,
      quantityList: null,
    },
    {
      id: "EVT-2025-0003",
      eventType: "AggregationEvent",
      bizStep: "packing",
      disposition: "in_progress",
      action: "ADD",
      eventTime: "2025-03-05T08:20:00Z",
      readPointId: "FAC-RTM-02",
      bizTransaction: "ASN-7721",
      shipmentId: "SHIP-1007",
      batchIds: ["LOT-AL-25-041", "LOT-PP-25-019"],
      assetIds: ["RTI-0007"],
      transformationId: null,
      inputBatchIds: null,
      outputBatchIds: null,
      epcList: ["urn:epc:id:sscc:0614141.0000000007"],
      quantityList: null,
    },
    {
      id: "EVT-2025-0004",
      eventType: "TransactionEvent",
      bizStep: "shipping",
      disposition: "in_transit",
      action: "ADD",
      eventTime: "2025-03-05T12:05:00Z",
      readPointId: "FAC-RTM-02",
      bizTransaction: "ASN-7721",
      shipmentId: "SHIP-1007",
      batchIds: ["LOT-AL-25-041"],
      assetIds: null,
      transformationId: null,
      inputBatchIds: null,
      outputBatchIds: null,
      epcList: ["urn:epc:id:sscc:0614141.1234567890"],
      quantityList: null,
    },
    {
      id: "EVT-2025-0005",
      eventType: "ObjectEvent",
      bizStep: "receiving",
      disposition: "available",
      action: "ADD",
      eventTime: "2025-03-12T09:10:00Z",
      readPointId: "FAC-RTM-02",
      bizTransaction: "BOL-5519",
      shipmentId: "SHIP-1011",
      batchIds: ["LOT-PET-25-010"],
      assetIds: ["RTI-0108"],
      transformationId: null,
      inputBatchIds: null,
      outputBatchIds: null,
      epcList: null,
      quantityList: null,
    },
    {
      id: "EVT-2025-0006",
      eventType: "ObjectEvent",
      bizStep: "repairing",
      disposition: "in_progress",
      action: "OBSERVE",
      eventTime: "2025-03-18T16:45:00Z",
      readPointId: "FAC-DET-03",
      bizTransaction: "RMA-2044",
      shipmentId: null,
      batchIds: null,
      assetIds: ["BAT-1001"],
      transformationId: null,
      inputBatchIds: null,
      outputBatchIds: null,
      epcList: null,
      quantityList: null,
    },
  ],
};
