export const FACILITIES = {
  list: [
    {
      id: "FAC-CHI-01",
      name: "Calumet Remelt Plant",
      type: "Remelt Plant",
      status: "Active",
      location: "Chicago, IL",
      gln: "0614141123456",
      operatorAccountId: "northloop-metals",
      processes: "commissioning, transforming, shipping, receiving",
      certifications: "ASI, ISO 14001",
      capacity: "42k tons/year",
      shiftPattern: "3 shifts",
      energyMix: "58% renewable",
      wasteDiversionRate: "92%",
      waterReuseRate: "38%",
      lastAuditDate: "2025-02-18",
    },
    {
      id: "FAC-PDX-04",
      name: "Cascade Plastics Reclaim",
      type: "Recycling Facility",
      status: "Active",
      location: "Portland, OR",
      gln: "0614141998801",
      operatorAccountId: "blueriver-plastics",
      processes: "receiving, disassembling, transforming, inspecting",
      certifications: "ISCC+, ISO 14001",
      capacity: "28k tons/year",
      shiftPattern: "2 shifts",
      energyMix: "76% renewable",
      wasteDiversionRate: "95%",
      waterReuseRate: "44%",
      lastAuditDate: "2025-01-30",
    },
    {
      id: "FAC-DET-03",
      name: "Renaissance Battery Hub",
      type: "Battery Refurb Hub",
      status: "Active",
      location: "Detroit, MI",
      gln: "0614141443322",
      operatorAccountId: "greenpulse-batteries",
      processes: "inspecting, repairing, decommissioning, commissioning",
      certifications: "R2v3, ISO 9001",
      capacity: "14k packs/year",
      shiftPattern: "2 shifts",
      energyMix: "41% renewable",
      wasteDiversionRate: "88%",
      waterReuseRate: "22%",
      lastAuditDate: "2025-02-05",
    },
    {
      id: "FAC-RTM-02",
      name: "Rotterdam Circular Port DC",
      type: "Distribution Center",
      status: "Active",
      location: "Rotterdam, NL",
      gln: "8712345001123",
      operatorAccountId: "ecovia-logistics",
      processes: "receiving, shipping, storing, loading",
      certifications: "ISO 14001, ISO 9001",
      capacity: "120k pallets",
      shiftPattern: "24/7",
      energyMix: "64% renewable",
      wasteDiversionRate: "85%",
      waterReuseRate: "18%",
      lastAuditDate: "2025-02-25",
    },
    {
      id: "FAC-MTY-07",
      name: "Monterrey Precision Plant",
      type: "Machining Plant",
      status: "Maintenance",
      location: "Monterrey, MX",
      gln: "0750002003344",
      operatorAccountId: "aurora-composites",
      processes: "commissioning, assembly, packing, shipping",
      certifications: "IATF 16949, ISO 9001",
      capacity: "18k assemblies/month",
      shiftPattern: "1 shift",
      energyMix: "23% renewable",
      wasteDiversionRate: "79%",
      waterReuseRate: "12%",
      lastAuditDate: "2024-12-12",
    },
    {
      id: "FAC-TUS-06",
      name: "Sonoran Repair Center",
      type: "Remanufacturing Center",
      status: "Active",
      location: "Tucson, AZ",
      gln: "0614141776655",
      operatorAccountId: "atlas-remanufacturing",
      processes: "repairing, inspecting, decommissioning, commissioning",
      certifications: "ISO 9001, ISO 14001",
      capacity: "9k units/year",
      shiftPattern: "2 shifts",
      energyMix: "52% renewable",
      wasteDiversionRate: "90%",
      waterReuseRate: "30%",
      lastAuditDate: "2025-02-01",
    },
    {
      id: "FAC-AUS-05",
      name: "Lone Star Automation Lab",
      type: "Automation Refurb Lab",
      status: "Active",
      location: "Austin, TX",
      gln: "0614141889921",
      operatorAccountId: "reclaim-robotics",
      processes: "inspecting, repairing, commissioning",
      certifications: "UL 508A, ISO 9001",
      capacity: "2k cells/year",
      shiftPattern: "1 shift",
      energyMix: "48% renewable",
      wasteDiversionRate: "87%",
      waterReuseRate: "16%",
      lastAuditDate: "2025-02-20",
    },
  ],
};
