export const MATERIALS = {
  list: [
    {
      id: "MAT-AL-5083",
      name: "Recycled Aluminum 5083",
      category: "Metal",
      grade: "5083-H116",
      form: "Billet",
      recycledContent: "82%",
      certification: "ASI Performance Standard",
      sourceType: "Post-industrial",
      defaultDisposition: "available",
      supplierAccountId: "northloop-metals",
      preferredFacilityId: "FAC-CHI-01",
      leadTime: "6-8 weeks",
      minOrderQty: "20,000 kg",
      materialPassportId: "MP-AL-5083-2025",
      epcClass: "urn:epc:class:lgtin:0614141.00011.400",
      endOfLifeRoute: "Closed-loop remelt",
    },
    {
      id: "MAT-STEEL-CR",
      name: "Cold-Rolled Steel Coil",
      category: "Metal",
      grade: "CR 1008",
      form: "Coil",
      recycledContent: "65%",
      certification: "ISO 14001",
      sourceType: "Post-consumer",
      defaultDisposition: "available",
      supplierAccountId: "atlas-remanufacturing",
      preferredFacilityId: "FAC-MTY-07",
      leadTime: "8-10 weeks",
      minOrderQty: "25,000 kg",
      materialPassportId: "MP-ST-1008-2025",
      epcClass: "urn:epc:class:lgtin:0614141.00022.200",
      endOfLifeRoute: "Scrap return to mill",
    },
    {
      id: "MAT-PET-R30",
      name: "rPET Flake 30%",
      category: "Plastic",
      grade: "rPET",
      form: "Flake",
      recycledContent: "30%",
      certification: "ISCC+",
      sourceType: "Post-consumer",
      defaultDisposition: "in_progress",
      supplierAccountId: "blueriver-plastics",
      preferredFacilityId: "FAC-PDX-04",
      leadTime: "7-9 weeks",
      minOrderQty: "10,000 kg",
      materialPassportId: "MP-PET-30-2025",
      epcClass: "urn:epc:class:lgtin:0614141.00033.100",
      endOfLifeRoute: "Bottle-to-bottle loop",
    },
    {
      id: "MAT-NMC-R",
      name: "Recovered NMC Cathode Powder",
      category: "Battery Materials",
      grade: "NMC-811",
      form: "Powder",
      recycledContent: "55%",
      certification: "R2v3",
      sourceType: "Post-consumer",
      defaultDisposition: "in_progress",
      supplierAccountId: "greenpulse-batteries",
      preferredFacilityId: "FAC-DET-03",
      leadTime: "10-12 weeks",
      minOrderQty: "2,000 kg",
      materialPassportId: "MP-NMC-811-2025",
      epcClass: "urn:epc:class:lgtin:0614141.00044.300",
      endOfLifeRoute: "Hydrometallurgical recovery",
    },
    {
      id: "MAT-PP-REGRIND",
      name: "PP Regrind Natural",
      category: "Plastic",
      grade: "PP-IM",
      form: "Regrind",
      recycledContent: "95%",
      certification: "UL 2809",
      sourceType: "Post-industrial",
      defaultDisposition: "available",
      supplierAccountId: "ecovia-logistics",
      preferredFacilityId: "FAC-RTM-02",
      leadTime: "2-3 weeks",
      minOrderQty: "5,000 kg",
      materialPassportId: "MP-PP-REGRIND-2025",
      epcClass: "urn:epc:class:lgtin:0614141.00055.600",
      endOfLifeRoute: "Reusable packaging pool",
    },
    {
      id: "MAT-CF-RECL",
      name: "Reclaimed Carbon Fiber",
      category: "Composite",
      grade: "T700",
      form: "Chopped fiber",
      recycledContent: "70%",
      certification: "ISO 14001",
      sourceType: "Post-industrial",
      defaultDisposition: "available",
      supplierAccountId: "circular-dynamics",
      preferredFacilityId: "FAC-RTM-02",
      leadTime: "12-14 weeks",
      minOrderQty: "1,000 kg",
      materialPassportId: "MP-CF-RECL-2025",
      epcClass: "urn:epc:class:lgtin:0614141.00066.800",
      endOfLifeRoute: "Composite reclaim program",
    },
  ],
};
