export const SHIPMENTS = {
  list: [
    {
      id: "SHIP-1007",
      status: "In Transit",
      bizStep: "shipping",
      disposition: "in_transit",
      carrier: "Maersk",
      mode: "Ocean + Rail",
      incoterms: "CIP Chicago",
      originFacilityId: "FAC-RTM-02",
      destinationFacilityId: "FAC-CHI-01",
      accountId: "northloop-metals",
      departureDate: "2025-03-05",
      eta: "2025-03-22",
      loadType: "FCL",
      trackingRef: "MAEU1234567",
      batchIds: ["LOT-AL-25-041", "LOT-PP-25-019"],
      assetIds: ["RTI-0007"],
      eventIds: ["EVT-2025-0003", "EVT-2025-0004"],
    },
    {
      id: "SHIP-1011",
      status: "Delivered",
      bizStep: "receiving",
      disposition: "available",
      carrier: "XPO Logistics",
      mode: "Truckload",
      incoterms: "DAP Rotterdam",
      originFacilityId: "FAC-PDX-04",
      destinationFacilityId: "FAC-RTM-02",
      accountId: "blueriver-plastics",
      departureDate: "2025-03-08",
      eta: "2025-03-12",
      loadType: "FTL",
      trackingRef: "XPO-458992",
      batchIds: ["LOT-PET-25-010"],
      assetIds: ["RTI-0108"],
      eventIds: ["EVT-2025-0005"],
    },
    {
      id: "SHIP-1014",
      status: "Exception",
      bizStep: "shipping",
      disposition: "damaged",
      carrier: "FedEx Freight",
      mode: "Hazmat LTL",
      incoterms: "DAP Detroit",
      originFacilityId: "FAC-MTY-07",
      destinationFacilityId: "FAC-DET-03",
      accountId: "greenpulse-batteries",
      departureDate: "2025-03-10",
      eta: "2025-03-18",
      loadType: "LTL",
      trackingRef: "FDX-774220",
      batchIds: ["LOT-NMC-25-002"],
      assetIds: ["BAT-1001"],
      eventIds: null,
    },
    {
      id: "SHIP-1022",
      status: "Pending",
      bizStep: "consigning",
      disposition: "in_progress",
      carrier: "Old Dominion",
      mode: "LTL",
      incoterms: "FOB Phoenix",
      originFacilityId: "FAC-TUS-06",
      destinationFacilityId: "FAC-RTM-02",
      accountId: "atlas-remanufacturing",
      departureDate: "2025-03-20",
      eta: "2025-03-27",
      loadType: "LTL",
      trackingRef: "ODFL-21009",
      batchIds: ["LOT-STEEL-25-007"],
      assetIds: ["RTI-0214"],
      eventIds: null,
    },
    {
      id: "SHIP-1030",
      status: "Delivered",
      bizStep: "receiving",
      disposition: "available",
      carrier: "DHL Supply Chain",
      mode: "Truckload",
      incoterms: "DAP Rotterdam",
      originFacilityId: "FAC-AUS-05",
      destinationFacilityId: "FAC-RTM-02",
      accountId: "circular-dynamics",
      departureDate: "2025-03-01",
      eta: "2025-03-06",
      loadType: "FTL",
      trackingRef: "DHL-8891",
      batchIds: ["LOT-CF-25-003"],
      assetIds: null,
      eventIds: null,
    },
  ],
};
