import { TASKS } from "@/lib/tasks";

export const INITIAL_DATA = {
  analytics: {
    revenue: 125000,
    growth: 0.15,
    customers: 1234,
    orders: 567,
    salesByRegion: [
      { label: "US", value: 45000 },
      { label: "EU", value: 35000 },
      { label: "Asia", value: 28000 },
      { label: "Other", value: 17000 },
    ],
    recentTransactions: [
      {
        id: "TXN001",
        customer: "Acme Corp",
        amount: 1500,
        status: "completed",
        date: "2024-01-15",
      },
      {
        id: "TXN002",
        customer: "Globex Inc",
        amount: 2300,
        status: "pending",
        date: "2024-01-14",
      },
      {
        id: "TXN003",
        customer: "Initech",
        amount: 890,
        status: "completed",
        date: "2024-01-13",
      },
      {
        id: "TXN004",
        customer: "Umbrella Co",
        amount: 4200,
        status: "completed",
        date: "2024-01-12",
      },
    ],
  },
  form: {
    dateRange: "",
    region: "",
    accountsSearch: "",
  },
  dashboard: {
    metrics: {
      totalRevenue: 1250,
      newCustomers: 1234,
      activeAccounts: 45678,
      growthRate: 0.045,
    },
    visitors: [
      { label: "Apr 2", value: 120 },
      { label: "Apr 7", value: 180 },
      { label: "Apr 12", value: 140 },
      { label: "Apr 17", value: 220 },
      { label: "Apr 22", value: 160 },
      { label: "Apr 27", value: 240 },
      { label: "May 2", value: 210 },
      { label: "May 7", value: 260 },
      { label: "May 12", value: 190 },
      { label: "May 17", value: 280 },
      { label: "May 22", value: 230 },
      { label: "May 27", value: 300 },
    ],
    sections: [
      {
        title: "Cover page",
        type: "Cover page",
        status: "In Progress",
        target: 18,
        limit: 5,
        reviewer: "Eddie Lake",
      },
      {
        title: "Table of contents",
        type: "Table of contents",
        status: "Done",
        target: 29,
        limit: 24,
        reviewer: "Eddie Lake",
      },
      {
        title: "Executive summary",
        type: "Narrative",
        status: "Done",
        target: 10,
        limit: 13,
        reviewer: "Eddie Lake",
      },
      {
        title: "Technical approach",
        type: "Narrative",
        status: "Done",
        target: 27,
        limit: 23,
        reviewer: "Jamik Tashpulatov",
      },
      {
        title: "Design",
        type: "Narrative",
        status: "In Progress",
        target: 2,
        limit: 16,
        reviewer: "Jamik Tashpulatov",
      },
    ],
  },
  accounts: {
    summary: {
      total: 24,
      active: 18,
      atRisk: 3,
      renewalsThisQuarter: 6,
    },
    list: [
      {
        id: "acme-corp",
        name: "Acme Corp",
        owner: "Jamie Fox",
        segment: "Enterprise",
        status: "Active",
        health: "Healthy",
        arr: 125000,
        renewalDate: "2025-06-15",
        primaryPlant: "Dayton, OH",
        productFocus: "Industrial fasteners",
        certifications: "ISO 9001, ISO 14001",
        leadTime: "6-8 weeks",
        incoterms: "FOB Cleveland",
        shippingMode: "LTL",
        preferredCarrier: "FedEx Freight",
        warehouseRegion: "Midwest DC",
        paymentTerms: "Net 45",
        minOrderValue: 25000,
        contractTerm: "24 months",
        forecastCadence: "Monthly",
      },
      {
        id: "globex",
        name: "Globex",
        owner: "Priya Shah",
        segment: "Enterprise",
        status: "At Risk",
        health: "Watch",
        arr: 98000,
        renewalDate: "2025-05-02",
        primaryPlant: "Monterrey, MX",
        productFocus: "Precision machining",
        certifications: "ISO 9001, IATF 16949",
        leadTime: "8-10 weeks",
        incoterms: "DAP Houston",
        shippingMode: "Truckload",
        preferredCarrier: "XPO Logistics",
        warehouseRegion: "Gulf Coast",
        paymentTerms: "Net 60",
        minOrderValue: 40000,
        contractTerm: "36 months",
        forecastCadence: "Monthly",
      },
      {
        id: "umbrella-co",
        name: "Umbrella Co",
        owner: "Liam Carter",
        segment: "Mid-Market",
        status: "Active",
        health: "Healthy",
        arr: 47000,
        renewalDate: "2025-08-19",
        primaryPlant: "Madison, WI",
        productFocus: "Injection molded parts",
        certifications: "ISO 9001",
        leadTime: "5-7 weeks",
        incoterms: "FOB Chicago",
        shippingMode: "LTL",
        preferredCarrier: "Old Dominion",
        warehouseRegion: "Great Lakes",
        paymentTerms: "Net 30",
        minOrderValue: 15000,
        contractTerm: "18 months",
        forecastCadence: "Quarterly",
      },
      {
        id: "initech",
        name: "Initech",
        owner: "Sofia Ramirez",
        segment: "Mid-Market",
        status: "Churn Risk",
        health: "Critical",
        arr: 32000,
        renewalDate: "2025-04-05",
        primaryPlant: "Austin, TX",
        productFocus: "Electromechanical assemblies",
        certifications: "ISO 9001, IPC-A-610",
        leadTime: "10-12 weeks",
        incoterms: "DAP Dallas",
        shippingMode: "Air + LTL",
        preferredCarrier: "UPS Freight",
        warehouseRegion: "South Central",
        paymentTerms: "Net 60",
        minOrderValue: 30000,
        contractTerm: "12 months",
        forecastCadence: "Monthly",
      },
      {
        id: "soylent",
        name: "Soylent",
        owner: "Marcus Lee",
        segment: "Enterprise",
        status: "Active",
        health: "Healthy",
        arr: 156000,
        renewalDate: "2025-11-30",
        primaryPlant: "Fresno, CA",
        productFocus: "Food-grade processing equipment",
        certifications: "ISO 22000, ISO 9001",
        leadTime: "7-9 weeks",
        incoterms: "FOB Oakland",
        shippingMode: "Reefer truck",
        preferredCarrier: "Ryder",
        warehouseRegion: "West Coast",
        paymentTerms: "Net 45",
        minOrderValue: 35000,
        contractTerm: "24 months",
        forecastCadence: "Monthly",
      },
      {
        id: "stark-industries",
        name: "Stark Industries",
        owner: "Nina Patel",
        segment: "Strategic",
        status: "Active",
        health: "Healthy",
        arr: 210000,
        renewalDate: "2025-09-12",
        primaryPlant: "Pittsburgh, PA",
        productFocus: "Advanced alloys",
        certifications: "AS9100, ISO 9001",
        leadTime: "12-14 weeks",
        incoterms: "FOB Baltimore",
        shippingMode: "Truckload",
        preferredCarrier: "Schneider",
        warehouseRegion: "Northeast",
        paymentTerms: "Net 45",
        minOrderValue: 75000,
        contractTerm: "48 months",
        forecastCadence: "Monthly",
      },
      {
        id: "wayne-enterprises",
        name: "Wayne Enterprises",
        owner: "Evan Reed",
        segment: "Strategic",
        status: "At Risk",
        health: "Watch",
        arr: 189000,
        renewalDate: "2025-07-03",
        primaryPlant: "Detroit, MI",
        productFocus: "Powertrain components",
        certifications: "IATF 16949, ISO 14001",
        leadTime: "9-11 weeks",
        incoterms: "DAP Detroit",
        shippingMode: "Rail + LTL",
        preferredCarrier: "CSX Logistics",
        warehouseRegion: "Midwest",
        paymentTerms: "Net 60",
        minOrderValue: 60000,
        contractTerm: "36 months",
        forecastCadence: "Monthly",
      },
      {
        id: "hooli",
        name: "Hooli",
        owner: "Sara Bennett",
        segment: "Mid-Market",
        status: "Active",
        health: "Healthy",
        arr: 54000,
        renewalDate: "2025-10-21",
        primaryPlant: "Portland, OR",
        productFocus: "Electronics assemblies",
        certifications: "ISO 9001, ISO 27001",
        leadTime: "6-8 weeks",
        incoterms: "FOB Seattle",
        shippingMode: "Parcel + LTL",
        preferredCarrier: "DHL Supply Chain",
        warehouseRegion: "Pacific Northwest",
        paymentTerms: "Net 30",
        minOrderValue: 20000,
        contractTerm: "18 months",
        forecastCadence: "Quarterly",
      },
    ],
  },
  settings: {
    profile: {
      name: "Alex Johnson",
      email: "alex.johnson@acme.com",
      title: "Product Lead",
      team: "Growth",
    },
    preferences: {
      timezone: "America/Los_Angeles",
      language: "en-US",
      dateFormat: "MMM d, yyyy",
      weekStart: "Monday",
      digest: "Weekly",
      quarterStart: "2025-01-01",
    },
    sessions: [
      {
        device: "MacBook Pro 16\"",
        location: "San Francisco, CA",
        lastActive: "2025-02-06",
        status: "Current",
      },
      {
        device: "iPhone 15 Pro",
        location: "San Jose, CA",
        lastActive: "2025-02-04",
        status: "Active",
      },
      {
        device: "Chrome on Windows",
        location: "New York, NY",
        lastActive: "2025-01-29",
        status: "Expired",
      },
    ],
  },
  tasks: {
    items: TASKS,
  },
};
