export type Task = {
  id: string;
  title: string;
  status: string;
  label: string;
  priority: string;
  assignee?: string;
  dueDate?: string;
  accountId?: string;
  facilityId?: string;
  shipmentId?: string;
  batchId?: string;
  materialId?: string;
  assetId?: string;
  eventId?: string;
  bizStep?: string;
  disposition?: string;
};

export const TASKS: Task[] = [
  {
    id: "TASK-2301",
    title: "Validate commissioning events for LOT-AL-25-041",
    status: "in progress",
    label: "traceability",
    priority: "high",
    assignee: "Riya Das",
    dueDate: "2025-04-02",
    accountId: "northloop-metals",
    facilityId: "FAC-CHI-01",
    batchId: "LOT-AL-25-041",
    eventId: "EVT-2025-0001",
    bizStep: "commissioning",
    disposition: "available",
  },
  {
    id: "TASK-2312",
    title: "Resolve non_conformant rPET lot LOT-PET-25-010",
    status: "todo",
    label: "quality",
    priority: "high",
    assignee: "Marcos Lin",
    dueDate: "2025-03-28",
    accountId: "blueriver-plastics",
    facilityId: "FAC-PDX-04",
    batchId: "LOT-PET-25-010",
    bizStep: "inspecting",
    disposition: "non_conformant",
  },
  {
    id: "TASK-2325",
    title: "Publish EPCIS 2.0 shipping feed for SHIP-1007",
    status: "backlog",
    label: "traceability",
    priority: "medium",
    assignee: "Yasmin Patel",
    accountId: "northloop-metals",
    shipmentId: "SHIP-1007",
    eventId: "EVT-2025-0003",
    bizStep: "shipping",
    disposition: "in_transit",
  },
  {
    id: "TASK-2335",
    title: "Add ISCC+ certificate to MAT-PET-R30 material passport",
    status: "todo",
    label: "quality",
    priority: "medium",
    assignee: "Haruto Sato",
    dueDate: "2025-03-26",
    accountId: "blueriver-plastics",
    materialId: "MAT-PET-R30",
  },
  {
    id: "TASK-2347",
    title: "Schedule RTI-0007 cleaning after 18 cycles",
    status: "done",
    label: "operations",
    priority: "low",
    assignee: "Elena Petrova",
    dueDate: "2025-03-05",
    assetId: "RTI-0007",
    facilityId: "FAC-RTM-02",
  },
  {
    id: "TASK-2352",
    title: "Investigate damaged disposition on SHIP-1014",
    status: "in progress",
    label: "operations",
    priority: "high",
    assignee: "Avery Clarke",
    shipmentId: "SHIP-1014",
    accountId: "greenpulse-batteries",
    disposition: "damaged",
  },
  {
    id: "TASK-2364",
    title: "Confirm transformation inputs for TR-AL-2025-041",
    status: "todo",
    label: "traceability",
    priority: "medium",
    assignee: "Sasha Ivanov",
    eventId: "EVT-2025-0002",
    batchId: "LOT-AL-25-041",
    bizStep: "transforming",
  },
  {
    id: "TASK-2370",
    title: "Calibrate sorting line at Cascade Plastics Reclaim",
    status: "backlog",
    label: "operations",
    priority: "medium",
    assignee: "Nora Kim",
    facilityId: "FAC-PDX-04",
  },
  {
    id: "TASK-2381",
    title: "Close takeback loop contract for Atlas Remanufacturing",
    status: "done",
    label: "operations",
    priority: "medium",
    assignee: "Liam Carter",
    accountId: "atlas-remanufacturing",
  },
  {
    id: "TASK-2392",
    title: "Review EPCIS event gaps for GreenPulse Batteries",
    status: "backlog",
    label: "traceability",
    priority: "high",
    assignee: "Priya Shah",
    accountId: "greenpulse-batteries",
  },
  {
    id: "TASK-2403",
    title: "Update GLN registry for FAC-DET-03",
    status: "todo",
    label: "traceability",
    priority: "low",
    assignee: "Kenji Rao",
    facilityId: "FAC-DET-03",
  },
  {
    id: "TASK-2411",
    title: "Audit storage conditions for LOT-STEEL-25-007",
    status: "in progress",
    label: "quality",
    priority: "medium",
    assignee: "Fatima Noor",
    dueDate: "2025-03-29",
    batchId: "LOT-STEEL-25-007",
    facilityId: "FAC-MTY-07",
    disposition: "damaged",
  },
  {
    id: "TASK-2420",
    title: "Prepare consignment docs for SHIP-1022",
    status: "todo",
    label: "operations",
    priority: "medium",
    assignee: "Grace Osei",
    dueDate: "2025-03-21",
    shipmentId: "SHIP-1022",
    bizStep: "consigning",
  },
  {
    id: "TASK-2433",
    title: "Validate repair cycle for BAT-1001",
    status: "done",
    label: "quality",
    priority: "high",
    assignee: "Omar Haddad",
    assetId: "BAT-1001",
    eventId: "EVT-2025-0006",
    bizStep: "repairing",
    disposition: "in_progress",
  },
  {
    id: "TASK-2445",
    title: "Reconcile material balances for MAT-AL-5083",
    status: "backlog",
    label: "operations",
    priority: "low",
    assignee: "Mia Chen",
    materialId: "MAT-AL-5083",
    facilityId: "FAC-CHI-01",
  },
  {
    id: "TASK-2456",
    title: "Investigate missing receiving event for SHIP-1011",
    status: "todo",
    label: "traceability",
    priority: "high",
    assignee: "Luca Romano",
    dueDate: "2025-03-25",
    shipmentId: "SHIP-1011",
    eventId: "EVT-2025-0005",
    bizStep: "receiving",
  },
  {
    id: "TASK-2462",
    title: "Approve recycled-content target update for Northloop Metals",
    status: "done",
    label: "operations",
    priority: "low",
    assignee: "Jamie Fox",
    accountId: "northloop-metals",
  },
  {
    id: "TASK-2470",
    title: "Assess non_conformant disposition on LOT-PET-25-010",
    status: "in progress",
    label: "quality",
    priority: "high",
    assignee: "Marcos Lin",
    batchId: "LOT-PET-25-010",
    disposition: "non_conformant",
  },
  {
    id: "TASK-2488",
    title: "Map transaction events to ASN-7721",
    status: "backlog",
    label: "traceability",
    priority: "medium",
    assignee: "Aya Ito",
    eventId: "EVT-2025-0004",
    bizStep: "shipping",
  },
  {
    id: "TASK-2493",
    title: "Stage RTI-0214 returns at FAC-TUS-06",
    status: "todo",
    label: "operations",
    priority: "medium",
    assignee: "Diego Ruiz",
    dueDate: "2025-03-24",
    assetId: "RTI-0214",
    facilityId: "FAC-TUS-06",
  },
  {
    id: "TASK-2501",
    title: "Review supplier COA for MAT-NMC-R",
    status: "todo",
    label: "quality",
    priority: "medium",
    assignee: "Sana Malik",
    materialId: "MAT-NMC-R",
    accountId: "greenpulse-batteries",
  },
  {
    id: "TASK-2515",
    title: "Close loop audit for Circular Dynamics",
    status: "canceled",
    label: "operations",
    priority: "low",
    assignee: "Noah Wilson",
    accountId: "circular-dynamics",
  },
  {
    id: "TASK-2523",
    title: "Update disposition to available for LOT-AL-25-042",
    status: "in progress",
    label: "quality",
    priority: "medium",
    assignee: "Riya Das",
    batchId: "LOT-AL-25-042",
    disposition: "in_progress",
  },
  {
    id: "TASK-2531",
    title: "Publish repair status updates to EPCIS events feed",
    status: "backlog",
    label: "traceability",
    priority: "low",
    assignee: "Ana Silva",
  },
];
